server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
